export enum EnvironmentEnum {
  DB_PATH = 'DB_PATH',
  FE_PATH = 'FE_PATH',
  DOWNLOADS_PATH = 'DOWNLOADS_PATH',
  FORMAT = 'FORMAT',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_RUN = 'REDIS_RUN',
  YT_COOKIES = 'YT_COOKIES',
  YT_COOKIES_FILE = 'YT_COOKIES_FILE',
  YT_SKIP_BURST_LIMIT = 'YT_SKIP_BURST_LIMIT',
  YT_SKIP_BURST_COOLDOWN_MS = 'YT_SKIP_BURST_COOLDOWN_MS',
}
